# Generated by Django 6.1.1 on 2026-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_student_branch_student_cgpa_student_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('Aptitude', 'Aptitude'), ('Coding', 'Coding'), ('Technical Interview', 'Technical Interview'), ('HR', 'HR'), ('Resume', 'Resume'), ('Eligibility', 'Eligibility'), ('Other', 'Other')], default='', max_length=50),
        ),
    ]
