# Generated by Django 6.1.1 on 2026-09-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_student_skill_level_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='required_skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
